version: "3.9"
name: fastapi_celery_resources

services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 30s
      timeout: 1m30s
      retries: 5
      start_period: 5s

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 30s
      timeout: 1m30s
      retries: 5
      start_period: 5s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - ${PGADMIN_PORT}:80
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  redis-data:
  postgres-data:
  pgadmin-data: