version: "3.9"

services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "-p", "6379", "ping"]
      interval: 30s
      timeout: 1m30s
      retries: 5
      start_period: 5s


volumes:
  redis-data: